import nodemailer from 'nodemailer';
import { reportFileName } from '@/lib/monthlyReport'
import { supabaseAdmin } from '@/lib/supabaseAdmin'

export const dynamic = 'force-dynamic'
export const revalidate = 0

// Emails a PDF that was already generated by /api/monthly-report.
// Does NOT touch Meta/Google APIs — just mails what the browser already has.
// Recipients come from meraki_report_recipients (configurable on the
// Reports tab) instead of being hardcoded — `kind` picks which flag column
// to filter on ('monthly' for the manual button, 'weekly' for the cron).
export async function POST(request) {
  try {
    const body = await request.json()
    const { start, end, label, pdfBase64, clients, overBudgetCount, kind } = body || {}

    if (!pdfBase64) {
      return Response.json({ ok: false, error: 'No report to email — generate one first.' }, { status: 400 })
    }
    if (!process.env.GMAIL_USER || !process.env.GMAIL_PASS) {
      return Response.json({ ok: false, error: 'Mail not configured (GMAIL_USER / GMAIL_PASS missing).' }, { status: 500 })
    }
    if (!start || !end) {
      return Response.json({ ok: false, error: 'Missing report date range.' }, { status: 400 })
    }

    const flagColumn = kind === 'weekly' ? 'weekly' : 'monthly'
    const db = supabaseAdmin()
    const { data: recipients, error: recErr } = await db
      .from('meraki_report_recipients')
      .select('email')
      .eq(flagColumn, true)
    if (recErr) return Response.json({ ok: false, error: `recipients: ${recErr.message}` }, { status: 500 })

    const toList = (recipients || []).map(r => r.email)
    if (toList.length === 0) {
      return Response.json({ ok: false, error: `No ${flagColumn} recipients configured — add one on the Reports tab.` }, { status: 400 })
    }

    const fileName = reportFileName({ start, end })

    const html = `
      <div style="font-family:Arial,sans-serif;color:#333">
        <div style="font-family:cursive;font-size:22px;margin-bottom:2px">
          <span style="color:#7DC242;font-weight:700">meraki</span><span style="color:#29ABE2;font-weight:700">ads</span>
        </div>
        <h2 style="color:#5a9c2f;margin-top:4px">${kind === 'weekly' ? 'Weekly' : 'Monthly'} Campaign Report — ${label}</h2>
        <p>${clients ?? '—'} clients${overBudgetCount ? ` · ${overBudgetCount} over budget` : ''}. Full per-campaign detail in the attached PDF.</p>
      </div>
    `

    const transporter = nodemailer.createTransport({
      host: 'smtp.gmail.com',
      port: 465,
      secure: true,
      auth: { user: process.env.GMAIL_USER, pass: process.env.GMAIL_PASS },
    })

    await transporter.sendMail({
      from: `"Meraki Ads Meta" <${process.env.GMAIL_USER}>`,
      to: toList,
      subject: `📊 ${kind === 'weekly' ? 'Weekly' : 'Monthly'} Campaign Report — ${label}${overBudgetCount ? ` — ${overBudgetCount} over budget` : ''}`,
      html,
      attachments: [{
        filename: fileName,
        content: Buffer.from(pdfBase64, 'base64'),
        contentType: 'application/pdf',
      }],
    })

    return Response.json({ ok: true, emailed: true, recipients: toList })
  } catch (e) {
    return Response.json({ ok: false, error: e.message }, { status: 500 })
  }
}
