import nodemailer from 'nodemailer';
import { reportFileName } from '@/lib/monthlyReport'

export const dynamic = 'force-dynamic'
export const revalidate = 0

// Emails a PDF that was already generated by /api/monthly-report.
// Does NOT touch Meta/Google APIs — just mails what the browser already has.
export async function POST(request) {
  try {
    const body = await request.json()
    const { month, label, pdfBase64, clients, overBudgetCount } = body || {}
    const fileName = reportFileName(month)

    if (!pdfBase64) {
      return Response.json({ ok: false, error: 'No report to email — generate one first.' }, { status: 400 })
    }
    if (!process.env.GMAIL_USER || !process.env.GMAIL_PASS) {
      return Response.json({ ok: false, error: 'Mail not configured (GMAIL_USER / GMAIL_PASS missing).' }, { status: 500 })
    }

    const html = `
      <div style="font-family:Arial,sans-serif;color:#333">
        <div style="font-family:cursive;font-size:22px;margin-bottom:2px">
          <span style="color:#7DC242;font-weight:700">meraki</span><span style="color:#29ABE2;font-weight:700">ads</span>
        </div>
        <h2 style="color:#5a9c2f;margin-top:4px">Monthly Campaign Report — ${label || month}</h2>
        <p>${clients ?? '—'} clients${overBudgetCount ? ` · ${overBudgetCount} over budget` : ''}. Full per-campaign detail in the attached PDF.</p>
      </div>
    `

    const transporter = nodemailer.createTransport({
      host: 'smtp.gmail.com',
      port: 465,
      secure: true,
      auth: { user: process.env.GMAIL_USER, pass: process.env.GMAIL_PASS },
    })

    await transporter.sendMail({
      from: `"Meraki Ads Meta" <${process.env.GMAIL_USER}>`,
      to: ['tusharchd29@gmail.com', 'heena@merakiads.in'],
      subject: `📊 Monthly Campaign Report — ${label || month}${overBudgetCount ? ` — ${overBudgetCount} over budget` : ''} (manual trigger)`,
      html,
      attachments: [{
        filename: fileName,
        content: Buffer.from(pdfBase64, 'base64'),
        contentType: 'application/pdf',
      }],
    })

    return Response.json({ ok: true, emailed: true })
  } catch (e) {
    return Response.json({ ok: false, error: e.message }, { status: 500 })
  }
}
